services:
  mongodb:
    image: mongo
    container_name: aahana-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    container_name: aahana-backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/studentProfileDB
    volumes:
      - ./backend:/app
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    container_name: aahana-frontend
    ports:
      - "3001:80"
    depends_on:
      - backend

volumes:
  mongo-data:
